spring:
  application:
    name: projectmanagement
  datasource:
    url: jdbc:mysql://localhost:3306/projectmanagement_test
    username: root
    password: thnbgmb3.1
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
      schema-locations: classpath:schema-test.sql
  mail:
    host: smtp.gmail.com
    port: 587
    username: hartmannti56011@gmail.com
    password: lgdk enju jqfz fmwd
    properties:
      mail:
        smtp:
          writetimeout: 5000
          connectiontimeout: 5000
          timeout: 5000
          auth: true
          starttls:
            enable: true
            required: true


jwt:
  secret: mysecret
  access-token-expiration-time: 86400000
  refresh-token-expiration-time: 3600000

server:
  error:
    path: /user/error
    whitelabel:
      enabled: false
